Squashed commit of the following:
commit ef1edb098c719c8df38663804c033588aa4166a3
Author: Etienne Dechamps <edechamps@google.com>
Date:   Wed Aug 26 08:44:27 2026 -0700

    Reland Cronet dependency version bump

    PiperOrigin-RevId: 971307374

commit 5af1f42cef0c9554c552ac3c4051b1b5ebd95611
Author: Etienne Dechamps <edechamps@google.com>
Date:   Tue Aug 25 06:13:35 2026 -0700

    Temporarily roll back Cronet dependency version bump

    PiperOrigin-RevId: 970506988

commit b68e2438dbb48d22cbb2e75f7b3eb7bf3aca007d
Author: Etienne Dechamps <edechamps@google.com>
Date:   Mon Aug 24 10:14:42 2026 -0700

    Bump Cronet dependency version

    PiperOrigin-RevId: 969928199

commit 4af96a602ac515ec331f0f6b17878126b7b583f9
Author: Vladyslav Kasprov <vkasprov@google.com>
Date:   Wed Jul 29 09:49:17 2026 -0700

    Make the bridge compatible with OkHttp 5+.

    PiperOrigin-RevId: 955936794

commit a5b55a21681b89c2554076666ec3ba0c14662123
Author: Mohannad Farrag <aymanm@google.com>
Date:   Thu Jul 23 05:38:09 2026 -0700

    Relax userAgentIsIncludedByDefault test by asserting on "Cronet/" rather than package name.

    PiperOrigin-RevId: 952704712

commit 30c30f032bd09506b69787580eb89e02d5092a5c
Author: Vladyslav Kasprov <vkasprov@google.com>
Date:   Fri Jul 17 06:31:51 2026 -0700

    Intended rollback of OkHttp 5+ compatibility. To be resubmitted again later.

    PiperOrigin-RevId: 949533997

commit 672e5d14be2eee9b92397be72b1758f48e028ba7
Author: Vladyslav Kasprov <vkasprov@google.com>
Date:   Fri Jul 17 04:07:06 2026 -0700

    Make the bridge compatible with OkHttp 5+.

    PiperOrigin-RevId: 949486826

commit 5c1069b29606356a06c322f783404477bd066124
Author: Etienne Dechamps <edechamps@google.com>
Date:   Wed Jul 8 08:32:40 2026 -0700

    Update min SDK from 23 to 24

    PiperOrigin-RevId: 944516723

commit 1e0f57ad50ca61f18fb72d9eaa3d051f753d22d3
Author: Cronet Developer <noreply@google.com>
Date:   Wed Jul 8 03:41:43 2026 -0700

    Update tests to run on API 24

    PiperOrigin-RevId: 944403608

commit c560480b7ce0fc68fe434f570b88f45fdc5afe90
Author: Vladyslav Kasprov <vkasprov@google.com>
Date:   Wed Jun 10 05:37:00 2026 -0700

    Remove null body assertions on secondary responses

    These assertions always pass in OkHttp 4 and always fail in OkHttp 5. Secondary response body used to be always null in OkHttp 4, but became always non-null in OkHttp 5. Remove the assertions to unblock OkHttp 5 support.

    PiperOrigin-RevId: 929789429

commit 08cd80807a0f1d9eea76de38eb788d88189c6eb2
Author: Etienne Dechamps <edechamps@google.com>
Date:   Mon Jun 8 08:31:02 2026 -0700

    Keep kotlin-stdlib classes in the main APK

    This fixes the following when depending on later Cronet versions, which end up indirectly depending on kotlin-stdlib through androidx:

    02:56:01.817	E	Act...ControllerCore	PROCESS CRASHED
    			processName: com.google.net.cronet.testing.testapp
    			pid: 4098
    			shortMsg: java.lang.ClassNotFoundException
    			longMsg: java.lang.ClassNotFoundException: Didn't find class "kotlin.LazyKt" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~K2-q1Ex0sAJeBQf2rgiwGw==/com.google.net.cronet.testing.testapp.test-PQ_3xigISy-l2t8fe-gl5A==/base.apk", zip file "/data/app/~~_6ay3nx3icud6A52KlVoSg==/com.google.net.cronet.testing.testapp-8WbsxOvc4FJ1HO6SI4pS-Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~K2-q1Ex0sAJeBQf2rgiwGw==/com.google.net.cronet.testing.testapp.test-PQ_3xigISy-l2t8fe-gl5A==/lib/x86_64, /data/app/~~_6ay3nx3icud6A52KlVoSg==/com.google.net.cronet.testing.testapp-8WbsxOvc4FJ1HO6SI4pS-Q==/lib/x86_64, /system/lib64, /system_ext/lib64]]
    			timeMillis: 1780912561813
    			stackTrace:
    			java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/LazyKt;
    			at androidx.test.platform.io.TestDirCalculator.<init>(TestDirCalculator.kt:30)
    			at androidx.test.platform.io.FileTestStorage.<init>(FileTestStorage.java:54)
    			at androidx.test.platform.io.PlatformTestStorageRegistry$$ExternalSyntheticLambda0.create(R8$$SyntheticClass:0)
    			at androidx.test.internal.platform.ServiceLoaderWrapper.loadSingleService(ServiceLoaderWrapper.java:76)
    			at androidx.test.platform.io.PlatformTestStorageRegistry.<clinit>(PlatformTestStorageRegistry.java:35)
    			at androidx.test.runner.AndroidJUnitRunner.registerTestStorage(AndroidJUnitRunner.java:683)
    			at androidx.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:321)
    			at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8131)
    			at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
    			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2690)
    			at android.os.Handler.dispatchMessage(Handler.java:132)
    			at android.os.Looper.dispatchMessage(Looper.java:333)
    			at android.os.Looper.loopOnce(Looper.java:263)
    			at android.os.Looper.loop(Looper.java:367)
    			at android.app.ActivityThread.main(ActivityThread.java:9287)
    			at java.lang.reflect.Method.invoke(Native Method)
    			at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
    			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
    PiperOrigin-RevId: 928579514

commit 2dff42add9e66172deaf085af0fd9f67996624ec
Author: Etienne Dechamps <edechamps@google.com>
Date:   Mon Jun 8 03:23:48 2026 -0700

    Bump compileSdk from 36 to 37 in Gradle projects

    PiperOrigin-RevId: 928456384

commit 430a40ad2395b5a656855244dd096d8a0cb20fef
Author: Etienne Dechamps <edechamps@google.com>
Date:   Mon Jun 8 03:00:55 2026 -0700

    Bump AGP to 9.1.1 in Gradle projects

    PiperOrigin-RevId: 928446892

commit 3c49981fcf6133271208e5e349dd5518028f207b
Author: Etienne Dechamps <edechamps@google.com>
Date:   Mon Jun 8 02:58:54 2026 -0700

    Remove <uses-sdk> from AndroidManifest.xml

    This resolves the following failure when upgrading to AGP 9:

    Execution failed for task ':sample:processDebugMainManifest'.
    > Manifest merger failed : The <uses-sdk> tag was detected in your main AndroidManifest.xml file. While its use is still permitted for specifying tools:overrideLibrary, it is no longer allowed for controlling SDK versions (e.g., targetSdkVersion, minSdkVersion). Starting with Android Gradle Plugin 9.0.0, these attributes have been deprecated within the manifest.

      To fix: Remove <uses-sdk> from your AndroidManifest.xml.

    PiperOrigin-RevId: 928446061

commit be879d8f6abdc597372856ba0fe5a7e8399bfcb5
Author: Etienne Dechamps <edechamps@google.com>
Date:   Sun Jun 7 10:19:15 2026 -0700

    Pull latest cronet-api in the test app

    PiperOrigin-RevId: 928153849

commit 5d99d4e97145361f6b146633e8720a016f2702bf
Author: Vladyslav Kasprov <vkasprov@google.com>
Date:   Thu May 7 08:03:54 2026 -0700

    Update OkHttp version used by the tests and sample app to 4.12.0

    PiperOrigin-RevId: 911966066

commit 9a041f7bd33d688090919d3c427e399bf47a1610
Author: Vladyslav Kasprov <vkasprov@google.com>
Date:   Thu May 7 06:59:40 2026 -0700

    Minor cleanup of build rules for tests

    - `cronet_test_helpers` target now explicitly lists all of its source files
    - `cronet_test_helpers` and `RequestBodyConverterTest` targets had unused dependencies removed

    PiperOrigin-RevId: 911940089

commit f587e7f115cec86d87c5efbab95de23d8681f3a1
Author: Etienne Dechamps <edechamps@google.com>
Date:   Wed Apr 29 07:07:45 2026 -0700

    Format Markdown files

    PiperOrigin-RevId: 907570374